### ISSUE TITLE
Transfer.java Caused by: java.lang.IllegalStateException: Unsupported metadata version: 13

### ISSUE THREAD

**Issue by paulvi** [emeraldpay/polkaj#67]
I am running examples/balance/src/main/java/Transfer.java
against locally running Polkadot node 0.9.7

```
% ./polkadot --dev -dPolkadotData
2021-09-08 16:11:00 Running in --dev mode, RPC CORS has been disabled.    
2021-09-08 16:11:00 Parity Polkadot    
2021-09-08 16:11:00 ✌️  version 0.9.7-5d35bac74-x86_64-macos  
```

And get only this output in 

```
16:10:02: Executing task ':balance:Transfer.main()'...

> Task :balance:compileJava UP-TO-DATE
> Task :balance:compileGroovy NO-SOURCE
> Task :balance:processResources NO-SOURCE
> Task :balance:classes UP-TO-DATE

> Task :balance:Transfer.main() FAILED
Connect to: ws://localhost:9944
Use standard accounts for Alice and Bob, expected to run against development network
Connected: true
Current height: 5873
Balance update. User: HNZata7iMYWmk5RvZRTiAsSDhV8366zq2YGb3tLH5Upf74F, new balance: 10,000.00 KSM

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
2 actionable tasks: 1 executed, 1 up-to-date
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access using Lookup on io.emeraldpay.polkaj.schnorrkel.SchnorrkelNative (file:/Users/paul/.m2/repository/io/emeraldpay/polkaj/polkaj-schnorrkel/0.4.0-SNAPSHOT/polkaj-schnorrkel-0.4.0-SNAPSHOT.jar) to class java.lang.ClassLoader
WARNING: Please consider reporting this to the maintainers of io.emeraldpay.polkaj.schnorrkel.SchnorrkelNative
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Unsupported metadata version: 13
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at Transfer.main(Transfer.java:108)
Caused by: java.lang.IllegalStateException: Unsupported metadata version: 13
	at io.emeraldpay.polkaj.scaletypes.MetadataReader.read(MetadataReader.java:23)
	at io.emeraldpay.polkaj.scaletypes.MetadataReader.read(MetadataReader.java:11)
	at io.emeraldpay.polkaj.scale.ScaleCodecReader.read(ScaleCodecReader.java:84)
	at io.emeraldpay.polkaj.scale.ScaleExtract.lambda$fromBytesData$1(ScaleExtract.java:42)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.emeraldpay.polkaj.apiws.PolkadotWsApi.accept(PolkadotWsApi.java:184)
	at io.emeraldpay.polkaj.apiws.PolkadotWsApi$3.onText(PolkadotWsApi.java:117)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.processText(WebSocketImpl.java:627)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$ReceiveTask.run(WebSocketImpl.java:435)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.tryChangeState(WebSocketImpl.java:853)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl$SignallingMessageConsumer.onText(WebSocketImpl.java:786)
	at java.net.http/jdk.internal.net.http.websocket.MessageDecoder.payloadData(MessageDecoder.java:222)
	at java.net.http/jdk.internal.net.http.websocket.Frame$Reader.readFrame(Frame.java:465)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReceiveTask.run(TransportImpl.java:665)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$TryEndDeferredCompleter.complete(SequentialScheduler.java:315)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$ReadEvent.handle(TransportImpl.java:762)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.checkEvents(RawChannelTube.java:174)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:204)
	at java.net.http/jdk.internal.net.http.RawChannelTube$ReadSubscriber.onNext(RawChannelTube.java:157)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:844)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:175)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:763)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:941)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:245)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:957)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:912)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:912)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':balance:Transfer.main()'.
> Process 'command '/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
16:10:03: Task execution finished ':balance:Transfer.main()'.
```

**Comment by paulvi** [comment]
I was running 0.4.0 SNAPSHOT current 705ece128edfa44b598e2a14de65aaae5b393f07

Trying 0.3.0 not possible over #64

**Comment by nschwermann** [comment]
duplicate https://github.com/emeraldpay/polkaj/issues/58
